import type {
  FitnessLevel,
  WorkoutDayFocus,
  WorkoutEquipment,
} from '@longeviq/shared';

export interface ExerciseTemplate {
  name: string;
  // The day focuses this exercise fits (a strength day uses exercises whose
  // focus list includes the day focus; cardio days pick cardio exercises).
  focus: WorkoutDayFocus[];
  // Minimum equipment required. NONE exercises are bodyweight-only.
  equipment: WorkoutEquipment;
  // Minimum fitness level required; harder variants gate harder patterns.
  minLevel: FitnessLevel;
  // Sets per level so beginners do less volume than advanced lifters.
  setsByLevel: Record<FitnessLevel, number>;
  // Canonical rep prescription (e.g. '8-12'). The planner shifts the range by
  // goal (endurance goals drift higher, hypertrophy stays in the classic zone).
  reps: string;
  restSeconds: number;
  notes?: string;
}

const BEGINNER = 'BEGINNER' as const;
const INTERMEDIATE = 'INTERMEDIATE' as const;
const ADVANCED = 'ADVANCED' as const;
const NONE = 'NONE' as const;
const BASIC = 'BASIC' as const;
const FULL_GYM = 'FULL_GYM' as const;
const FULL_BODY = 'FULL_BODY' as const;
const UPPER_BODY = 'UPPER_BODY' as const;
const LOWER_BODY = 'LOWER_BODY' as const;
const PUSH = 'PUSH' as const;
const PULL = 'PULL' as const;
const LEGS = 'LEGS' as const;
const CORE = 'CORE' as const;
const CARDIO = 'CARDIO' as const;

export const EXERCISE_CATALOG: ExerciseTemplate[] = [
  // --- Full body -----------------------------------------------------------
  {
    name: 'Bodyweight squats',
    focus: [FULL_BODY, LEGS, LOWER_BODY],
    equipment: NONE,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 5 },
    reps: '12-15',
    restSeconds: 60,
    notes: 'Keep your heels down and knees tracking over your toes.',
  },
  {
    name: 'Push-ups',
    focus: [FULL_BODY, PUSH, UPPER_BODY],
    equipment: NONE,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 5 },
    reps: '8-12',
    restSeconds: 60,
    notes: 'Lower your chest to the floor with a straight line from head to heels.',
  },
  {
    name: 'Reverse lunges',
    focus: [FULL_BODY, LEGS, LOWER_BODY],
    equipment: NONE,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 5 },
    reps: '10-12 per leg',
    restSeconds: 60,
    notes: 'Step back and lower until both knees are near 90 degrees.',
  },
  {
    name: 'Glute bridges',
    focus: [FULL_BODY, LEGS, LOWER_BODY],
    equipment: NONE,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 4 },
    reps: '15-20',
    restSeconds: 45,
    notes: 'Drive through your heels and squeeze the glutes at the top.',
  },
  {
    name: 'Mountain climbers',
    focus: [FULL_BODY],
    equipment: NONE,
    minLevel: INTERMEDIATE,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 4 },
    reps: '30-45 sec',
    restSeconds: 45,
    notes: 'Keep hips low and drive your knees toward your chest.',
  },
  {
    name: 'Burpees',
    focus: [FULL_BODY],
    equipment: NONE,
    minLevel: ADVANCED,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 4 },
    reps: '8-12',
    restSeconds: 90,
    notes: 'Jump back to plank, chest to floor, then jump up with a soft landing.',
  },
  {
    name: 'Dumbbell thrusters',
    focus: [FULL_BODY],
    equipment: BASIC,
    minLevel: INTERMEDIATE,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 4 },
    reps: '10-12',
    restSeconds: 75,
    notes: 'Squat with dumbbells at the shoulders, then press overhead as you stand.',
  },
  {
    name: 'Kettlebell swings',
    focus: [FULL_BODY],
    equipment: BASIC,
    minLevel: INTERMEDIATE,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 4 },
    reps: '12-15',
    restSeconds: 60,
    notes: 'Hip-hinge explosively; the swing should come from the hips, not the arms.',
  },
  {
    name: 'Barbell clean and press',
    focus: [FULL_BODY],
    equipment: FULL_GYM,
    minLevel: ADVANCED,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 5 },
    reps: '6-8',
    restSeconds: 120,
    notes: 'Drive from the legs to rack the bar, then press overhead.',
  },

  // --- Push ----------------------------------------------------------------
  {
    name: 'Knee push-ups',
    focus: [PUSH, UPPER_BODY, FULL_BODY],
    equipment: NONE,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 3 },
    reps: '10-15',
    restSeconds: 60,
    notes: 'Start from your knees for an approachable push-up variation.',
  },
  {
    name: 'Incline push-ups',
    focus: [PUSH, UPPER_BODY],
    equipment: NONE,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 4 },
    reps: '10-15',
    restSeconds: 60,
    notes: 'Hands on a bench or table; the higher the incline, the easier the push.',
  },
  {
    name: 'Tricep dips',
    focus: [PUSH, UPPER_BODY],
    equipment: NONE,
    minLevel: INTERMEDIATE,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 4 },
    reps: '8-12',
    restSeconds: 60,
    notes: 'Use a sturdy chair or bench; keep elbows pointing back.',
  },
  {
    name: 'Pike push-ups',
    focus: [PUSH, UPPER_BODY],
    equipment: NONE,
    minLevel: INTERMEDIATE,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 4 },
    reps: '8-10',
    restSeconds: 75,
    notes: 'Hips high in a pike position; lower the crown of your head toward the floor.',
  },
  {
    name: 'Handstand push-ups',
    focus: [PUSH],
    equipment: NONE,
    minLevel: ADVANCED,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 5 },
    reps: '5-8',
    restSeconds: 120,
    notes: 'Against a wall for safety; lower your head between your hands.',
  },
  {
    name: 'Dumbbell shoulder press',
    focus: [PUSH, UPPER_BODY],
    equipment: BASIC,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 4 },
    reps: '8-12',
    restSeconds: 75,
    notes: 'Press from shoulder height without arching your lower back.',
  },
  {
    name: 'Dumbbell chest press',
    focus: [PUSH, UPPER_BODY],
    equipment: BASIC,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 4 },
    reps: '8-12',
    restSeconds: 75,
    notes: 'Lie on a bench, press up from the chest, and lower with control.',
  },
  {
    name: 'Overhead press',
    focus: [PUSH, UPPER_BODY],
    equipment: FULL_GYM,
    minLevel: INTERMEDIATE,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 5 },
    reps: '6-10',
    restSeconds: 90,
    notes: 'Brace your core and press the bar overhead from the front rack.',
  },
  {
    name: 'Bench press',
    focus: [PUSH, UPPER_BODY],
    equipment: FULL_GYM,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 5 },
    reps: '6-10',
    restSeconds: 90,
    notes: 'Feet planted, shoulder blades pinched; a spotter is recommended.',
  },

  // --- Pull ----------------------------------------------------------------
  {
    name: 'Superman holds',
    focus: [PULL, UPPER_BODY, FULL_BODY],
    equipment: NONE,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 3 },
    reps: '20-30 sec',
    restSeconds: 45,
    notes: 'Lying face down, lift arms and legs to work the whole posterior chain.',
  },
  {
    name: 'Reverse snow angels',
    focus: [PULL, UPPER_BODY],
    equipment: NONE,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 3 },
    reps: '10-12',
    restSeconds: 45,
    notes: 'Lying face down, sweep arms in a slow snow-angel motion.',
  },
  {
    name: 'Prone Y-T-W raises',
    focus: [PULL, UPPER_BODY],
    equipment: NONE,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 3 },
    reps: '8-10 per position',
    restSeconds: 60,
    notes: 'Lying face down, raise your arms through Y, T, and W positions.',
  },
  {
    name: 'Inverted rows',
    focus: [PULL, UPPER_BODY],
    equipment: BASIC,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 4 },
    reps: '8-12',
    restSeconds: 75,
    notes: 'Under a sturdy table or low bar, pull your chest to the edge.',
  },
  {
    name: 'Pull-ups',
    focus: [PULL, UPPER_BODY],
    equipment: BASIC,
    minLevel: INTERMEDIATE,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 5 },
    reps: '6-10',
    restSeconds: 120,
    notes: 'Dead hang to chin over the bar; use a band for assistance if needed.',
  },
  {
    name: 'Dumbbell rows',
    focus: [PULL, UPPER_BODY],
    equipment: BASIC,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 4 },
    reps: '8-12 per side',
    restSeconds: 75,
    notes: 'Hinge forward and row the dumbbell to your hip without twisting.',
  },
  {
    name: 'Face pulls',
    focus: [PULL, UPPER_BODY],
    equipment: BASIC,
    minLevel: INTERMEDIATE,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 4 },
    reps: '12-15',
    restSeconds: 60,
    notes: 'Pull a band or rope to your face and squeeze the shoulder blades.',
  },
  {
    name: 'Lat pulldowns',
    focus: [PULL, UPPER_BODY],
    equipment: FULL_GYM,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 4 },
    reps: '8-12',
    restSeconds: 75,
    notes: 'Pull the bar to your collarbone, elbows driving down and back.',
  },
  {
    name: 'Barbell rows',
    focus: [PULL, UPPER_BODY],
    equipment: FULL_GYM,
    minLevel: INTERMEDIATE,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 5 },
    reps: '6-10',
    restSeconds: 90,
    notes: 'Hinge forward with a flat back and row the bar to your belly.',
  },
  {
    name: 'Seated cable rows',
    focus: [PULL, UPPER_BODY],
    equipment: FULL_GYM,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 4 },
    reps: '8-12',
    restSeconds: 75,
    notes: 'Sit tall, pull the handle to your torso, and squeeze the back.',
  },

  // --- Legs ----------------------------------------------------------------
  {
    name: 'Bodyweight squats',
    focus: [LEGS, LOWER_BODY, FULL_BODY],
    equipment: NONE,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 5 },
    reps: '12-15',
    restSeconds: 60,
    notes: 'Sit back into the squat with a proud chest and neutral spine.',
  },
  {
    name: 'Reverse lunges',
    focus: [LEGS, LOWER_BODY, FULL_BODY],
    equipment: NONE,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 5 },
    reps: '10-12 per leg',
    restSeconds: 60,
    notes: 'Step back and lower until both knees are near 90 degrees.',
  },
  {
    name: 'Glute bridges',
    focus: [LEGS, LOWER_BODY, FULL_BODY],
    equipment: NONE,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 4 },
    reps: '15-20',
    restSeconds: 45,
    notes: 'Drive through your heels and squeeze the glutes at the top.',
  },
  {
    name: 'Calf raises',
    focus: [LEGS, LOWER_BODY],
    equipment: NONE,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 4 },
    reps: '15-20',
    restSeconds: 45,
    notes: 'Rise onto the balls of your feet and pause at the top.',
  },
  {
    name: 'Step-ups',
    focus: [LEGS, LOWER_BODY],
    equipment: NONE,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 4 },
    reps: '10-12 per leg',
    restSeconds: 60,
    notes: 'Use a sturdy step or bench and drive through the leading heel.',
  },
  {
    name: 'Bulgarian split squats',
    focus: [LEGS, LOWER_BODY],
    equipment: NONE,
    minLevel: INTERMEDIATE,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 4 },
    reps: '8-12 per leg',
    restSeconds: 75,
    notes: 'Rear foot on a bench, lower straight down on the front leg.',
  },
  {
    name: 'Goblet squats',
    focus: [LEGS, LOWER_BODY],
    equipment: BASIC,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 4 },
    reps: '8-12',
    restSeconds: 75,
    notes: 'Hold a dumbbell at your chest and squat with an upright torso.',
  },
  {
    name: 'Dumbbell Romanian deadlifts',
    focus: [LEGS, LOWER_BODY],
    equipment: BASIC,
    minLevel: INTERMEDIATE,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 4 },
    reps: '8-12',
    restSeconds: 90,
    notes: 'Hinge at the hips, keeping a flat back, and lower the weights to mid-shin.',
  },
  {
    name: 'Barbell back squats',
    focus: [LEGS, LOWER_BODY],
    equipment: FULL_GYM,
    minLevel: INTERMEDIATE,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 5 },
    reps: '6-10',
    restSeconds: 120,
    notes: 'Unrack with a braced core and squat to at least parallel.',
  },
  {
    name: 'Barbell deadlifts',
    focus: [LEGS, LOWER_BODY, FULL_BODY],
    equipment: FULL_GYM,
    minLevel: ADVANCED,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 5 },
    reps: '5-8',
    restSeconds: 150,
    notes: 'Hinge the bar off the floor with a flat back and neutral spine.',
  },
  {
    name: 'Leg press',
    focus: [LEGS, LOWER_BODY],
    equipment: FULL_GYM,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 4, ADVANCED: 5 },
    reps: '10-15',
    restSeconds: 90,
    notes: 'Lower the platform until your knees approach 90 degrees.',
  },

  // --- Core ----------------------------------------------------------------
  {
    name: 'Plank',
    focus: [CORE, FULL_BODY],
    equipment: NONE,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 4 },
    reps: '30-45 sec',
    restSeconds: 45,
    notes: 'Keep a straight line from head to heels; do not let hips sag.',
  },
  {
    name: 'Bicycle crunches',
    focus: [CORE],
    equipment: NONE,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 4 },
    reps: '12-15 per side',
    restSeconds: 45,
    notes: 'Rotate shoulder to opposite knee in a slow, controlled bicycle motion.',
  },
  {
    name: 'Dead bugs',
    focus: [CORE],
    equipment: NONE,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 3 },
    reps: '8-10 per side',
    restSeconds: 45,
    notes: 'Press your lower back into the floor while extending opposite limbs.',
  },
  {
    name: 'Side planks',
    focus: [CORE],
    equipment: NONE,
    minLevel: INTERMEDIATE,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 4 },
    reps: '20-30 sec per side',
    restSeconds: 45,
    notes: 'Stack your hips and keep a straight line from head to feet.',
  },
  {
    name: 'Russian twists',
    focus: [CORE],
    equipment: NONE,
    minLevel: INTERMEDIATE,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 4 },
    reps: '12-15 per side',
    restSeconds: 45,
    notes: 'Rotate the torso side to side with a tall spine and soft knees.',
  },
  {
    name: 'Flutter kicks',
    focus: [CORE],
    equipment: NONE,
    minLevel: INTERMEDIATE,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 4 },
    reps: '20-30 sec',
    restSeconds: 45,
    notes: 'Lie on your back with hands under hips and keep kicks small and steady.',
  },
  {
    name: 'Weighted planks',
    focus: [CORE],
    equipment: BASIC,
    minLevel: ADVANCED,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 4 },
    reps: '30-45 sec',
    restSeconds: 60,
    notes: 'Add a plate or weight on your lower back to increase the challenge.',
  },
  {
    name: 'Cable woodchoppers',
    focus: [CORE],
    equipment: FULL_GYM,
    minLevel: INTERMEDIATE,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 4 },
    reps: '10-12 per side',
    restSeconds: 60,
    notes: 'Pull a high cable diagonally across the body to the opposite hip.',
  },
  {
    name: 'Hanging knee raises',
    focus: [CORE],
    equipment: FULL_GYM,
    minLevel: ADVANCED,
    setsByLevel: { BEGINNER: 3, INTERMEDIATE: 3, ADVANCED: 4 },
    reps: '8-12',
    restSeconds: 60,
    notes: 'Hang from a bar and raise your knees to your chest without swinging.',
  },

  // --- Cardio --------------------------------------------------------------
  {
    name: 'Brisk walking',
    focus: [CARDIO],
    equipment: NONE,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 1, INTERMEDIATE: 1, ADVANCED: 1 },
    reps: 'steady pace',
    restSeconds: 0,
    notes: 'Walk at a pace where you can talk but feel slightly out of breath.',
  },
  {
    name: 'Jogging',
    focus: [CARDIO],
    equipment: NONE,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 1, INTERMEDIATE: 1, ADVANCED: 1 },
    reps: 'steady pace',
    restSeconds: 0,
    notes: 'Keep a comfortable conversational pace for the full session.',
  },
  {
    name: 'Jump rope',
    focus: [CARDIO],
    equipment: NONE,
    minLevel: INTERMEDIATE,
    setsByLevel: { BEGINNER: 1, INTERMEDIATE: 1, ADVANCED: 1 },
    reps: 'intervals',
    restSeconds: 0,
    notes: 'Jump 60 seconds, recover 30 seconds, and repeat for the session.',
  },
  {
    name: 'Stair climbing',
    focus: [CARDIO, LEGS, LOWER_BODY],
    equipment: NONE,
    minLevel: INTERMEDIATE,
    setsByLevel: { BEGINNER: 1, INTERMEDIATE: 1, ADVANCED: 1 },
    reps: 'steady pace',
    restSeconds: 0,
    notes: 'Climb stairs at a steady rhythm; use the handrail only for balance.',
  },
  {
    name: 'Swimming',
    focus: [CARDIO],
    equipment: NONE,
    minLevel: INTERMEDIATE,
    setsByLevel: { BEGINNER: 1, INTERMEDIATE: 1, ADVANCED: 1 },
    reps: 'lengths',
    restSeconds: 0,
    notes: 'Alternate strokes and take short rests between sets of lengths.',
  },
  {
    name: 'Stationary cycling',
    focus: [CARDIO],
    equipment: BASIC,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 1, INTERMEDIATE: 1, ADVANCED: 1 },
    reps: 'steady pace',
    restSeconds: 0,
    notes: 'Keep a steady cadence; raise resistance gradually.',
  },
  {
    name: 'Rowing machine',
    focus: [CARDIO],
    equipment: FULL_GYM,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 1, INTERMEDIATE: 1, ADVANCED: 1 },
    reps: 'steady pace',
    restSeconds: 0,
    notes: 'Drive with the legs, swing through the hips, and pull to the ribs.',
  },
  {
    name: 'Elliptical trainer',
    focus: [CARDIO],
    equipment: FULL_GYM,
    minLevel: BEGINNER,
    setsByLevel: { BEGINNER: 1, INTERMEDIATE: 1, ADVANCED: 1 },
    reps: 'steady pace',
    restSeconds: 0,
    notes: 'Keep an upright posture and push through the heels.',
  },
  {
    name: 'Interval running',
    focus: [CARDIO],
    equipment: NONE,
    minLevel: ADVANCED,
    setsByLevel: { BEGINNER: 1, INTERMEDIATE: 1, ADVANCED: 1 },
    reps: 'intervals',
    restSeconds: 0,
    notes: 'Alternate fast running with easy recovery jogs for the session.',
  },
];
